sources:
  cli:
    flags:
      - "--sources"
      - "-s"
    nargs: "+"  # multiple sources collected into list, at least one required
    help: "location of raw data sources. Sources can be folders or files.
      Multiple sources can be entered after this argument. 
      At least one source must be given if this argument is used.
      If this argument is not used, the converter GUI is launched"
config:
  cli:
    flags:
      - "--config"
      - "-c"
    help: "location of YAML configuration file. 
      This file will override any default configuration file, 
      and will be overridden by any arguments given here"
destination:
  cli:
    flags:
      - "--destination"
      - "-d"
    help: "destination folder for converted data. 
      Each raw data source makes a separate folder within the destination folder 
      with the same name as the source"
fresh_destination:
  config: 
    allowed_types:
      - 'bool'
    default: false
    gui:
      title: "Clear existing destination folders"
      control: 'checkbox'
      order: 90
  cli:
    flags:
      - '--fresh-destination'
      - '-f'
    action: 'store_true'
    help: "delete any previous conversion files if they exist"
move_files:
  config:
    allowed_types:
      - 'bool'
    default: false
    gui:
      title: "Move raw data files (instead of copying)"
      control: 'checkbox'
      order: 95
  cli:
    flags:
      - '--move-files'
    action: 'store_true'
    help: 'Move raw CAEN data files instead of copying them'
files_limit:
  config: 
    allowed_types:
      - 'none'
      - 'int'
    default: null
  cli:
    flags:
      - '--files-limit'
      - '-l'
    type: 'int'
    help: "limit number of original files processed. 
      Omit this (or use 0) for no limit (process all files in folder)"
caen_tasks:
  config:
    allowed_types:
      - 'int'
    default: 1
    gui:
      title: "Max simultaneous CAEN data file to Parquet conversions"
      control: 'spin'
      order: 40
  cli:
    flags:
      '--csv-tasks'
    type: 'int'
    help: "max number of simultaneous CAEN data file to Parquet conversions.
      Use 0 to do as many tasks as possible on this machine"
caen_timeout:
  config:
    allowed_types:
      - 'int'
    default: 120
    gui:
      title: "Max allowable time for each CAEN data file to Parquet conversion"
      control: 'spin'
      order: 50
  cli:
    flags:
      '--csv-timeout'
    type: 'int'
    help: "timeout for converting a CAEN data file to Parquet. 
      Use 0 for no timeout"
small_files:
  config: 
    allowed_types:
      - 'bool'
    default: false
    gui:
      title: "Handle small CSV files in parallel"
      control: 'checkbox'
      order: 85
  cli:
    flags:
      - "--small-files"
    action: 'store_true'
    help: "handle small CAEN CSV files in parallel. 
      When this is set, multiple CSV files will be converted simultaneously.
      When this is not set, CSV files will be read one by one, 
      but as parallel chunks."
mem_use_threshold:
  config:
    allowed_types:
      - 'int'
    default: 512
    gui:
      title: "Memory use threshold for conversion (in MB)"
      control: 'spin'
      order: 80
  cli:
    flags:
      - "--mem-use-threshold"
    type: 'int'
    help: "memory use threshold for conversion (in MB). 
      Files are converted in batches sized to use less than this amount of 
      memory if possible. Use 0 for no memory limit."
text_ui:
  cli:
    flags:
      - "--text-ui"
    action: 'store_true'
    help: "show text UI, including progress bars.
      If GUI is used (i.e. sources are not provided), 
      partial text UI (i.e. progress bars) is always shown, 
      and this argument has no effect."